// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.client;

/**
 * For Queries which do not provide a result set, this is returned on completion instead.
 */

public final class CommandStatus implements QueryResult {

  private final int statementId;
  private final String status;
  private final long updateCount;
  private final long insertOID;

  @Override
  public int statementId() {
    return this.statementId;
  }

  @Override
  public QueryResultKind getKind() {
    return QueryResultKind.STATUS;
  }

  @java.lang.SuppressWarnings("all")
  public CommandStatus(final int statementId, final String status, final long updateCount, final long insertOID) {
    this.statementId = statementId;
    this.status = status;
    this.updateCount = updateCount;
    this.insertOID = insertOID;
  }

  @java.lang.SuppressWarnings("all")
  public int getStatementId() {
    return this.statementId;
  }

  @java.lang.SuppressWarnings("all")
  public String getStatus() {
    return this.status;
  }

  @java.lang.SuppressWarnings("all")
  public long getUpdateCount() {
    return this.updateCount;
  }

  @java.lang.SuppressWarnings("all")
  public long getInsertOID() {
    return this.insertOID;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this)
      return true;
    if (!(o instanceof CommandStatus))
      return false;
    final CommandStatus other = (CommandStatus) o;
    if (this.getStatementId() != other.getStatementId())
      return false;
    final java.lang.Object this$status = this.getStatus();
    final java.lang.Object other$status = other.getStatus();
    if (this$status == null ? other$status != null
                            : !this$status.equals(other$status))
      return false;
    if (this.getUpdateCount() != other.getUpdateCount())
      return false;
    if (this.getInsertOID() != other.getInsertOID())
      return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = (result * PRIME) + this.getStatementId();
    final java.lang.Object $status = this.getStatus();
    result =
      (result * PRIME)
        + ($status == null ? 43
                           : $status.hashCode());
    final long $updateCount = this.getUpdateCount();
    result = (result * PRIME) + (int) (($updateCount >>> 32) ^ $updateCount);
    final long $insertOID = this.getInsertOID();
    result = (result * PRIME) + (int) (($insertOID >>> 32) ^ $insertOID);
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "CommandStatus(statementId="
      + this.getStatementId()
      + ", status="
      + this.getStatus()
      + ", updateCount="
      + this.getUpdateCount()
      + ", insertOID="
      + this.getInsertOID()
      + ")";
  }
}
