// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.client;

import java.util.Arrays;
import java.util.List;

/**
 * A single SQL statement.
 */
public class SimpleQuery implements Query {
  private final int paramcount;
  private final String sql;

  public SimpleQuery(String sql) {
    this(sql, 0);
  }

  public SimpleQuery(String sql, int paramcount) {
    this.sql = sql;
    this.paramcount = paramcount;
  }

  @Override
  public List<SimpleQuery> getSubqueries() {
    return Arrays.asList(this);
  }

  @Override
  public int parameterCount() {
    return this.paramcount;
  }

  /**
   * The SQL this query represents.
   */
  public String sql() {
    return this.sql;
  }

  public String toString() {
    return this.sql;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof SimpleQuery)) return false;
    final SimpleQuery other = (SimpleQuery) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (this.paramcount != other.paramcount) return false;
    final java.lang.Object this$sql = this.sql;
    final java.lang.Object other$sql = other.sql;
    if (this$sql == null ? other$sql != null : !this$sql.equals(other$sql)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof SimpleQuery;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.paramcount;
    final java.lang.Object $sql = this.sql;
    result = result * PRIME + ($sql == null ? 43 : $sql.hashCode());
    return result;
  }
}
