// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public class AuthenticationUnknown implements AuthenticationPacket {
  private int authType;

  public AuthenticationUnknown(int authType) {
    this.authType = authType;
  }

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitAuthenticationUnknown(this);
  }

  public String toString() {
    return String.format("Authentication(%s)", AuthType.fromInt(authType));
  }

  @java.lang.SuppressWarnings("all")
  public int getAuthType() {
    return this.authType;
  }
}
