// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import org.postgresql.core.Utils;

public class AuthenticationMD5Password implements AuthenticationPacket {
  private byte[] salt;

  public AuthenticationMD5Password(byte[] salt) {
    this.salt = salt;
  }

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitAuthenticationMD5Password(this);
  }

  public String toString() {
    return String.format("AuthenticationMD5Password(%s)", Utils.toHexString(salt));
  }

  @java.lang.SuppressWarnings("all")
  public byte[] getSalt() {
    return this.salt;
  }
}
