// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class BackendKeyData implements PostgreSQLPacket {
  private final int processId;
  private final int secret;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitBackendKeyData(this);
  }

  @java.lang.SuppressWarnings("all")
  public BackendKeyData(final int processId, final int secret) {
    this.processId = processId;
    this.secret = secret;
  }

  @java.lang.SuppressWarnings("all")
  public int getProcessId() {
    return this.processId;
  }

  @java.lang.SuppressWarnings("all")
  public int getSecret() {
    return this.secret;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof BackendKeyData)) return false;
    final BackendKeyData other = (BackendKeyData) o;
    if (this.getProcessId() != other.getProcessId()) return false;
    if (this.getSecret() != other.getSecret()) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getProcessId();
    result = result * PRIME + this.getSecret();
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "BackendKeyData(processId=" + this.getProcessId() + ", secret=" + this.getSecret() + ")";
  }
}
