// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class CommandComplete implements PostgreSQLPacket {
  private final String commandTag;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitCommandComplete(this);
  }

  @java.lang.SuppressWarnings("all")
  public CommandComplete(final String commandTag) {
    this.commandTag = commandTag;
  }

  @java.lang.SuppressWarnings("all")
  public String getCommandTag() {
    return this.commandTag;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof CommandComplete)) return false;
    final CommandComplete other = (CommandComplete) o;
    final java.lang.Object this$commandTag = this.getCommandTag();
    final java.lang.Object other$commandTag = other.getCommandTag();
    if (this$commandTag == null ? other$commandTag != null : !this$commandTag.equals(other$commandTag)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $commandTag = this.getCommandTag();
    result = result * PRIME + ($commandTag == null ? 43 : $commandTag.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "CommandComplete(commandTag=" + this.getCommandTag() + ")";
  }
}
