// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import java.util.List;

public final class DataRow implements PostgreSQLPacket {
  private final List<String> data;

  @Override
  public <T> T apply(final PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitDataRow(this);
  }

  @Override
  public String toString() {
    return "DataRow(" + data.size() + ")";
  }

  @java.lang.SuppressWarnings("all")
  public DataRow(final List<String> data) {
    this.data = data;
  }

  @java.lang.SuppressWarnings("all")
  public List<String> getData() {
    return this.data;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof DataRow)) return false;
    final DataRow other = (DataRow) o;
    final java.lang.Object this$data = this.getData();
    final java.lang.Object other$data = other.getData();
    if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $data = this.getData();
    result = result * PRIME + ($data == null ? 43 : $data.hashCode());
    return result;
  }
}
