// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class Execute implements PostgreSQLPacket {
  private final String command;
  private final int maxRows;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitExecute(this);
  }

  @java.lang.SuppressWarnings("all")
  public Execute(final String command, final int maxRows) {
    this.command = command;
    this.maxRows = maxRows;
  }

  @java.lang.SuppressWarnings("all")
  public String getCommand() {
    return this.command;
  }

  @java.lang.SuppressWarnings("all")
  public int getMaxRows() {
    return this.maxRows;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Execute)) return false;
    final Execute other = (Execute) o;
    final java.lang.Object this$command = this.getCommand();
    final java.lang.Object other$command = other.getCommand();
    if (this$command == null ? other$command != null : !this$command.equals(other$command)) return false;
    if (this.getMaxRows() != other.getMaxRows()) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $command = this.getCommand();
    result = result * PRIME + ($command == null ? 43 : $command.hashCode());
    result = result * PRIME + this.getMaxRows();
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Execute(command=" + this.getCommand() + ", maxRows=" + this.getMaxRows() + ")";
  }
}
