// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import java.util.List;

public class NoticeResponse implements PostgreSQLPacket {
  private List<String> messages;

  public NoticeResponse(List<String> messages) {
    this.messages = messages;
  }

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitNoticeResponse(this);
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "NoticeResponse(messages=" + this.getMessages() + ")";
  }

  @java.lang.SuppressWarnings("all")
  public List<String> getMessages() {
    return this.messages;
  }
}
