// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class ParameterStatus implements PostgreSQLPacket {
  private final String key;
  private final String value;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitParameterStatus(this);
  }

  @java.lang.SuppressWarnings("all")
  public ParameterStatus(final String key, final String value) {
    this.key = key;
    this.value = value;
  }

  @java.lang.SuppressWarnings("all")
  public String getKey() {
    return this.key;
  }

  @java.lang.SuppressWarnings("all")
  public String getValue() {
    return this.value;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof ParameterStatus)) return false;
    final ParameterStatus other = (ParameterStatus) o;
    final java.lang.Object this$key = this.getKey();
    final java.lang.Object other$key = other.getKey();
    if (this$key == null ? other$key != null : !this$key.equals(other$key)) return false;
    final java.lang.Object this$value = this.getValue();
    final java.lang.Object other$value = other.getValue();
    if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $key = this.getKey();
    result = result * PRIME + ($key == null ? 43 : $key.hashCode());
    final java.lang.Object $value = this.getValue();
    result = result * PRIME + ($value == null ? 43 : $value.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "ParameterStatus(key=" + this.getKey() + ", value=" + this.getValue() + ")";
  }
}
