// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import java.util.List;
import com.google.common.collect.ImmutableList;

public class Parse implements PostgreSQLPacket {
  private String name;
  private String query;
  private List<Integer> paramOids;

  public Parse(final String name, final String query) {
    this.name = name;
    this.query = query;
    this.paramOids = ImmutableList.of();
  }

  public Parse(final String name, final String query, final List<Integer> paramOids) {
    this.name = name;
    this.query = query;
    this.paramOids = ImmutableList.copyOf(paramOids);
  }

  @Override
  public <T> T apply(final PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitParse(this);
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Parse)) return false;
    final Parse other = (Parse) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$name = this.getName();
    final java.lang.Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    final java.lang.Object this$query = this.getQuery();
    final java.lang.Object other$query = other.getQuery();
    if (this$query == null ? other$query != null : !this$query.equals(other$query)) return false;
    final java.lang.Object this$paramOids = this.getParamOids();
    final java.lang.Object other$paramOids = other.getParamOids();
    if (this$paramOids == null ? other$paramOids != null : !this$paramOids.equals(other$paramOids)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Parse;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $name = this.getName();
    result = result * PRIME + ($name == null ? 43 : $name.hashCode());
    final java.lang.Object $query = this.getQuery();
    result = result * PRIME + ($query == null ? 43 : $query.hashCode());
    final java.lang.Object $paramOids = this.getParamOids();
    result = result * PRIME + ($paramOids == null ? 43 : $paramOids.hashCode());
    return result;
  }

  @java.lang.SuppressWarnings("all")
  public String getName() {
    return this.name;
  }

  @java.lang.SuppressWarnings("all")
  public String getQuery() {
    return this.query;
  }

  @java.lang.SuppressWarnings("all")
  public List<Integer> getParamOids() {
    return this.paramOids;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Parse(name=" + this.getName() + ", query=" + this.getQuery() + ", paramOids=" + this.getParamOids() + ")";
  }
}
