// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class PasswordMessage implements PostgreSQLPacket {
  private final byte[] password;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitPasswordMessage(this);
  }

  @java.lang.SuppressWarnings("all")
  public PasswordMessage(final byte[] password) {
    this.password = password;
  }

  @java.lang.SuppressWarnings("all")
  public byte[] getPassword() {
    return this.password;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof PasswordMessage)) return false;
    final PasswordMessage other = (PasswordMessage) o;
    if (!java.util.Arrays.equals(this.getPassword(), other.getPassword())) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + java.util.Arrays.hashCode(this.getPassword());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "PasswordMessage(password=" + java.util.Arrays.toString(this.getPassword()) + ")";
  }
}
