// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class Query implements PostgreSQLPacket {
  private final String query;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitQuery(this);
  }

  @java.lang.SuppressWarnings("all")
  public Query(final String query) {
    this.query = query;
  }

  @java.lang.SuppressWarnings("all")
  public String getQuery() {
    return this.query;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Query)) return false;
    final Query other = (Query) o;
    final java.lang.Object this$query = this.getQuery();
    final java.lang.Object other$query = other.getQuery();
    if (this$query == null ? other$query != null : !this$query.equals(other$query)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $query = this.getQuery();
    result = result * PRIME + ($query == null ? 43 : $query.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Query(query=" + this.getQuery() + ")";
  }
}
