// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

public final class ReadyForQuery implements PostgreSQLPacket {
  private final TransactionStatus status;

  @Override
  public <T> T apply(final PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitReadyForQuery(this);
  }

  @java.lang.SuppressWarnings("all")
  public ReadyForQuery(final TransactionStatus status) {
    this.status = status;
  }

  @java.lang.SuppressWarnings("all")
  public TransactionStatus getStatus() {
    return this.status;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof ReadyForQuery)) return false;
    final ReadyForQuery other = (ReadyForQuery) o;
    final java.lang.Object this$status = this.getStatus();
    final java.lang.Object other$status = other.getStatus();
    if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $status = this.getStatus();
    result = result * PRIME + ($status == null ? 43 : $status.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "ReadyForQuery(status=" + this.getStatus() + ")";
  }
}
