// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import java.util.List;

public final class RowDescription implements PostgreSQLPacket {

  public static final class Entry {
    private final String name;

    @java.lang.SuppressWarnings("all")
    public Entry(final String name) {
      this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
      return this.name;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof RowDescription.Entry)) return false;
      final RowDescription.Entry other = (RowDescription.Entry) o;
      final java.lang.Object this$name = this.getName();
      final java.lang.Object other$name = other.getName();
      if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $name = this.getName();
      result = result * PRIME + ($name == null ? 43 : $name.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
      return "RowDescription.Entry(name=" + this.getName() + ")";
    }
  }

  private final List<Entry> rows;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitRowDescription(this);
  }

  @java.lang.SuppressWarnings("all")
  public RowDescription(final List<Entry> rows) {
    this.rows = rows;
  }

  @java.lang.SuppressWarnings("all")
  public List<Entry> getRows() {
    return this.rows;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof RowDescription)) return false;
    final RowDescription other = (RowDescription) o;
    final java.lang.Object this$rows = this.getRows();
    final java.lang.Object other$rows = other.getRows();
    if (this$rows == null ? other$rows != null : !this$rows.equals(other$rows)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $rows = this.getRows();
    result = result * PRIME + ($rows == null ? 43 : $rows.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "RowDescription(rows=" + this.getRows() + ")";
  }
}
