// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import java.util.Map;

public final class StartupMessage implements PostgreSQLPacket {
  private final int majorVersion;
  private final int minorVersion;
  private final Map<String, String> parameters;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitStartupMessage(this);
  }

  @java.lang.SuppressWarnings("all")
  public StartupMessage(final int majorVersion, final int minorVersion, final Map<String, String> parameters) {
    this.majorVersion = majorVersion;
    this.minorVersion = minorVersion;
    this.parameters = parameters;
  }

  @java.lang.SuppressWarnings("all")
  public int getMajorVersion() {
    return this.majorVersion;
  }

  @java.lang.SuppressWarnings("all")
  public int getMinorVersion() {
    return this.minorVersion;
  }

  @java.lang.SuppressWarnings("all")
  public Map<String, String> getParameters() {
    return this.parameters;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof StartupMessage)) return false;
    final StartupMessage other = (StartupMessage) o;
    if (this.getMajorVersion() != other.getMajorVersion()) return false;
    if (this.getMinorVersion() != other.getMinorVersion()) return false;
    final java.lang.Object this$parameters = this.getParameters();
    final java.lang.Object other$parameters = other.getParameters();
    if (this$parameters == null ? other$parameters != null : !this$parameters.equals(other$parameters)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getMajorVersion();
    result = result * PRIME + this.getMinorVersion();
    final java.lang.Object $parameters = this.getParameters();
    result = result * PRIME + ($parameters == null ? 43 : $parameters.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "StartupMessage(majorVersion=" + this.getMajorVersion() + ", minorVersion=" + this.getMinorVersion() + ", parameters=" + this.getParameters() + ")";
  }
}
