// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.wire;

import io.zrz.jpgsql.proto.netty.MessageType;

public final class UnknownMessage implements PostgreSQLPacket {
  private final MessageType type;

  @Override
  public <T> T apply(PostgreSQLPacketVisitor<T> visitor) {
    return visitor.visitUnknownMessage(this);
  }

  @java.lang.SuppressWarnings("all")
  public UnknownMessage(final MessageType type) {
    this.type = type;
  }

  @java.lang.SuppressWarnings("all")
  public MessageType getType() {
    return this.type;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof UnknownMessage)) return false;
    final UnknownMessage other = (UnknownMessage) o;
    final java.lang.Object this$type = this.getType();
    final java.lang.Object other$type = other.getType();
    if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $type = this.getType();
    result = result * PRIME + ($type == null ? 43 : $type.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "UnknownMessage(type=" + this.getType() + ")";
  }
}
