// Generated by delombok at Tue Sep 22 10:54:18 PDT 2020
package io.zrz.jpgsql.proto.replication;

import io.netty.buffer.ByteBuf;

public class XLogData {
  private final long startingPoint;
  private final long currentEnd;
  private final long txtime;
  private final ByteBuf byteBuf;

  public XLogData(final long startingPoint, final long currentEnd, final long txtime, final ByteBuf byteBuf) {
    this.startingPoint = startingPoint;
    this.currentEnd = currentEnd;
    this.txtime = txtime;
    this.byteBuf = byteBuf;
  }

  public long getStartingPoint() {
    return this.startingPoint;
  }

  public long getCurrentEnd() {
    return this.currentEnd;
  }

  public long getTxTime() {
    return this.txtime;
  }

  public ByteBuf getByteBuf() {
    return this.byteBuf;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "XLogData(startingPoint=" + this.getStartingPoint() + ", currentEnd=" + this.getCurrentEnd() + ", txtime=" + this.getTxTime() + ", byteBuf=" + this.getByteBuf() + ")";
  }
}
