name: Java CI with Gradle
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --warning-mode all -PversionId="$(git rev-parse --short HEAD)" assemble
    - name: Publish to BinTray
      run: ./gradlew --warning-mode all -PversionId="$(git rev-parse --short HEAD)" bintrayUpload
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
